configuration: Release
os: Visual Studio 2015 RC
environment:
  VisualStudioVersion: 14.0
  DNX_FEED: https://www.nuget.org/api/v2
install:
  - dnvm upgrade
  - dnu restore
  - dnu pack src/Nine.Formatting --configuration Release --out artifacts
  - dnx test\Nine.Formatting.Test test
build: off
artifacts:
  - path: artifacts\**\*.nupkg
